name: xpatch
channels:
 - pytorch
 - nvidia
 - defaults
dependencies:
  - python=3.8.19
  - cudatoolkit=11.7.0
  - pytorch=2.0.1
  - pip:
    - git+https://github.com/davidbau/baukit@main#egg=baukit
    - git+https://github.com/TIGER-AI-Lab/Mantis.git
    - accelerate==0.33.0
    - bitsandbytes==0.43.1
    - datasets==2.18.0
    - huggingface-hub==0.23.4
    - matplotlib==3.7.5
    - numpy==1.24.4
    - omegaconf==2.1.1
    - pandas==2.0.3
    - protobuf==3.20.3
    - scikit-learn==1.3.2
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - transformers==4.44.2
    - tqdm==4.66.4